[package]
name = "prime-sieve-w30"
version = "0.1.0"
edition = "2021"
authors = ["Hannah Cheng <> (GitHub: hannah-cheng)"]
license = "MIT"
description = "A high-performance implementation of the Segmented Sieve of Eratosthenes with Wheel-30 optimization, designed for large-scale prime counting experiments in computational number theory (verified up to 1e11 and potentially scalable to 1e12). Intended for academic research and reproducibility."
repository = "https://github.com/hannah-cheng/eratosthenes-segmented-prime-sieve-wheel30"
readme = "README.md"

[dependencies]
